<?php

return [
    ['country' => 'Afeganistão', 'capital' => 'Cabul'],
    ['country' => 'África do Sul', 'capital' => 'Pretória'],
    ['country' => 'Albânia', 'capital' => 'Tirana'],
    ['country' => 'Alemanha', 'capital' => 'Berlim'],
    ['country' => 'Andorra', 'capital' => 'Andorra-a-Velha'],
    ['country' => 'Angola', 'capital' => 'Luanda'],
    ['country' => 'Antígua e Barbuda', 'capital' => 'São João'],
    ['country' => 'Arábia Saudita', 'capital' => 'Riade'],
    ['country' => 'Argélia', 'capital' => 'Argel'],
    ['country' => 'Argentina', 'capital' => 'Buenos Aires'],
    ['country' => 'Armênia', 'capital' => 'Erevã'],
    ['country' => 'Austrália', 'capital' => 'Camberra'],
    ['country' => 'Áustria', 'capital' => 'Viena'],
    ['country' => 'Azerbaijão', 'capital' => 'Baku'],
    ['country' => 'Bahamas', 'capital' => 'Nassau'],
    ['country' => 'Bangladesh', 'capital' => 'Daca'],
    ['country' => 'Barbados', 'capital' => 'Bridgetown'],
    ['country' => 'Bahrein', 'capital' => 'Manama'],
    ['country' => 'Bélgica', 'capital' => 'Bruxelas'],
    ['country' => 'Belize', 'capital' => 'Belmopan'],
    ['country' => 'Benim', 'capital' => 'Porto Novo'],
    ['country' => 'Bielorrússia', 'capital' => 'Minsk'],
    ['country' => 'Bolívia', 'capital' => 'Sucre'],
    ['country' => 'Bósnia e Herzegovina', 'capital' => 'Saraievo'],
    ['country' => 'Botsuana', 'capital' => 'Gaborone'],
    ['country' => 'Brasil', 'capital' => 'Brasília'],
    ['country' => 'Brunei', 'capital' => 'Bandar Seri Begawan'],
    ['country' => 'Bulgária', 'capital' => 'Sófia'],
    ['country' => 'Burquina Fasso', 'capital' => 'Uagadugu'],
    ['country' => 'Burundi', 'capital' => 'Bujumbura'],
    ['country' => 'Butão', 'capital' => 'Timbu'],
    ['country' => 'Cabo Verde', 'capital' => 'Praia'],
    ['country' => 'Camarões', 'capital' => 'Yaoundé'],
    ['country' => 'Camboja', 'capital' => 'Phnom Penh'],
    ['country' => 'Canadá', 'capital' => 'Ottawa'],
    ['country' => 'Catar', 'capital' => 'Doha'],
    ['country' => 'Cazaquistão', 'capital' => 'Nursultan'],
    ['country' => 'Chade', 'capital' => 'Jamena'],
    ['country' => 'Chile', 'capital' => 'Santiago'],
    ['country' => 'China', 'capital' => 'Pequim'],
    ['country' => 'Chipre', 'capital' => 'Nicósia'],
    ['country' => 'Colômbia', 'capital' => 'Bogotá'],
    ['country' => 'Comores', 'capital' => 'Moroni'],
    ['country' => 'Congo-Brazzaville', 'capital' => 'Brazzaville'],
    ['country' => 'Congo-Kinshasa', 'capital' => 'Kinshasa'],
    ['country' => 'Coreia do Norte', 'capital' => 'Pyongyang'],
    ['country' => 'Coreia do Sul', 'capital' => 'Seul'],
    ['country' => 'Cosovo', 'capital' => 'Pristina'],
    ['country' => 'Costa do Marfim', 'capital' => 'Yamoussoukro'],
    ['country' => 'Costa Rica', 'capital' => 'São José'],
    ['country' => 'Croácia', 'capital' => 'Zagreb'],
    ['country' => 'Kuwait', 'capital' => 'Cidade do Kuwait'],
    ['country' => 'Cuba', 'capital' => 'Havana'],
    ['country' => 'Dinamarca', 'capital' => 'Copenhague'],
    ['country' => 'Dominica', 'capital' => 'Roseau'],
    ['country' => 'Egito', 'capital' => 'Cairo'],
    ['country' => 'Emirados Árabes Unidos', 'capital' => 'Abu Dhabi'],
    ['country' => 'Equador', 'capital' => 'Quito'],
    ['country' => 'Eritreia', 'capital' => 'Asmara'],
    ['country' => 'Eslováquia', 'capital' => 'Bratislava'],
    ['country' => 'Eslovênia', 'capital' => 'Liubliana'],
    ['country' => 'Espanha', 'capital' => 'Madrid'],
    ['country' => 'Estados Unidos', 'capital' => 'Washington'],
    ['country' => 'Estônia', 'capital' => 'Talim'],
    ['country' => 'Etiópia', 'capital' => 'Adis Abeba'],
    ['country' => 'Fiji', 'capital' => 'Suva'],
    ['country' => 'Filipinas', 'capital' => 'Manila'],
    ['country' => 'Finlândia', 'capital' => 'Helsínquia'],
    ['country' => 'França', 'capital' => 'Paris'],
    ['country' => 'Gabão', 'capital' => 'Libreville'],
    ['country' => 'Gâmbia', 'capital' => 'Banjul'],
    ['country' => 'Gana', 'capital' => 'Acra'],
    ['country' => 'Geórgia', 'capital' => 'Tbilisi'],
    ['country' => 'Granada', 'capital' => 'São Jorge'],
    ['country' => 'Grécia', 'capital' => 'Atenas'],
    ['country' => 'Guatemala', 'capital' => 'Cidade da Guatemala'],
    ['country' => 'Guiana', 'capital' => 'Georgetown'],
    ['country' => 'Guiné', 'capital' => 'Conacri'],
    ['country' => 'Guiné Equatorial', 'capital' => 'Malabo'],
    ['country' => 'Guiné-Bissau', 'capital' => 'Bissau'],
    ['country' => 'Haiti', 'capital' => 'Porto Príncipe'],
    ['country' => 'Holanda', 'capital' => 'Amsterdã'],
    ['country' => 'Honduras', 'capital' => 'Tegucigalpa'],
    ['country' => 'Hungria', 'capital' => 'Budapeste'],
    ['country' => 'Iêmen', 'capital' => 'Sana'],
    ['country' => 'Ilhas Marechal', 'capital' => 'Majuro'],
    ['country' => 'Índia', 'capital' => 'Nova Deli'],
    ['country' => 'Indonésia', 'capital' => 'Jacarta'],
    ['country' => 'Irã', 'capital' => 'Teerã'],
    ['country' => 'Iraque', 'capital' => 'Bagdade'],
    ['country' => 'Irlanda', 'capital' => 'Dublin'],
    ['country' => 'Islândia', 'capital' => 'Reykjavik'],
    ['country' => 'Jamaica', 'capital' => 'Kingston'],
    ['country' => 'Japão', 'capital' => 'Tóquio'],
    ['country' => 'Djibuti', 'capital' => 'Djibuti'],
    ['country' => 'Jordânia', 'capital' => 'Amã'],
    ['country' => 'Kuwait', 'capital' => 'Cidade do Kuwait'],
    ['country' => 'Laos', 'capital' => 'Vientiane'],
    ['country' => 'Lesoto', 'capital' => 'Maseru'],
    ['country' => 'Letônia', 'capital' => 'Riga'],
    ['country' => 'Líbano', 'capital' => 'Beirute'],
    ['country' => 'Libéria', 'capital' => 'Monróvia'],
    ['country' => 'Líbia', 'capital' => 'Trípoli'],
    ['country' => 'Liechtenstein', 'capital' => 'Vaduz'],
    ['country' => 'Lituânia', 'capital' => 'Vilnius'],
    ['country' => 'Luxemburgo', 'capital' => 'Luxemburgo'],
    ['country' => 'Macedônia do Norte', 'capital' => 'Escópia'],
    ['country' => 'Madagascar', 'capital' => 'Antananarivo'],
    ['country' => 'Malásia', 'capital' => 'Kuala Lumpur'],
    ['country' => 'Malawi', 'capital' => 'Lilongwe'],
    ['country' => 'Maldivas', 'capital' => 'Malé'],
    ['country' => 'Mali', 'capital' => 'Bamako'],
    ['country' => 'Malta', 'capital' => 'Valeta'],
    ['country' => 'Marrocos', 'capital' => 'Rabat'],
    ['country' => 'Maurício', 'capital' => 'Port Louis'],
    ['country' => 'Mauritânia', 'capital' => 'Nouakchott'],
    ['country' => 'México', 'capital' => 'Cidade do México'],
    ['country' => 'Mianmar', 'capital' => 'Naypyidaw'],
    ['country' => 'Micronésia', 'capital' => 'Palikir'],
    ['country' => 'Moçambique', 'capital' => 'Maputo'],
    ['country' => 'Moldávia', 'capital' => 'Chisinau'],
    ['country' => 'Mônaco', 'capital' => 'Mônaco'],
    ['country' => 'Mongólia', 'capital' => 'Ulaanbaatar'],
    ['country' => 'Montenegro', 'capital' => 'Podgorica'],
    ['country' => 'Namíbia', 'capital' => 'Windhoek'],
    ['country' => 'Nauru', 'capital' => 'Yaren'],
    ['country' => 'Nepal', 'capital' => 'Catmandu'],
    ['country' => 'Nicarágua', 'capital' => 'Manágua'],
    ['country' => 'Níger', 'capital' => 'Niamey'],
    ['country' => 'Nigéria', 'capital' => 'Abuja'],
    ['country' => 'Noruega', 'capital' => 'Oslo'],
    ['country' => 'Nova Zelândia', 'capital' => 'Wellington'],
    ['country' => 'Omã', 'capital' => 'Mascate'],
    ['country' => 'Países Baixos', 'capital' => 'Amsterdã'],
    ['country' => 'Palau', 'capital' => 'Ngerulmud'],
    ['country' => 'Panamá', 'capital' => 'Cidade do Panamá'],
    ['country' => 'Papua Nova Guiné', 'capital' => 'Port Moresby'],
    ['country' => 'Paquistão', 'capital' => 'Islamabad'],
    ['country' => 'Paraguai', 'capital' => 'Assunção'],
    ['country' => 'Peru', 'capital' => 'Lima'],
    ['country' => 'Polônia', 'capital' => 'Varsóvia'],
    ['country' => 'Portugal', 'capital' => 'Lisboa'],
    ['country' => 'Quênia', 'capital' => 'Nairóbi'],
    ['country' => 'Quirguistão', 'capital' => 'Bishkek'],
    ['country' => 'Quiribati', 'capital' => 'Tarawa do Sul'],
    ['country' => 'Reino Unido', 'capital' => 'Londres'],
    ['country' => 'República Centro-Africana', 'capital' => 'Bangui'],
    ['country' => 'República Tcheca', 'capital' => 'Praga'],
    ['country' => 'República Dominicana', 'capital' => 'Santo Domingo'],
    ['country' => 'Romênia', 'capital' => 'Bucareste'],
    ['country' => 'Ruanda', 'capital' => 'Kigali'],
    ['country' => 'Rússia', 'capital' => 'Moscou'],
    ['country' => 'Ilhas Salomão', 'capital' => 'Honiara'],
    ['country' => 'El Salvador', 'capital' => 'San Salvador'],
    ['country' => 'Samoa', 'capital' => 'Apia'],
    ['country' => 'Santa Lúcia', 'capital' => 'Castries'],
    ['country' => 'São Cristóvão e Névis', 'capital' => 'Basseterre'],
    ['country' => 'São Marinho', 'capital' => 'São Marinho'],
    ['country' => 'São Tomé e Príncipe', 'capital' => 'São Tomé'],
    ['country' => 'São Vicente e Granadinas', 'capital' => 'Kingstown'],
    ['country' => 'Seychelles', 'capital' => 'Victoria'],
    ['country' => 'Senegal', 'capital' => 'Dacar'],
    ['country' => 'Serra Leoa', 'capital' => 'Freetown'],
    ['country' => 'Sérvia', 'capital' => 'Belgrado'],
    ['country' => 'Singapura', 'capital' => 'Singapura'],
    ['country' => 'Síria', 'capital' => 'Damasco'],
    ['country' => 'Somália', 'capital' => 'Mogadíscio'],
    ['country' => 'Sri Lanka', 'capital' => 'Sri Jayawardenapura Kotte'],
    ['country' => 'Essuatíni', 'capital' => 'Lobamba'],
    ['country' => 'Sudão', 'capital' => 'Cartum'],
    ['country' => 'Sudão do Sul', 'capital' => 'Juba'],
    ['country' => 'Suécia', 'capital' => 'Estocolmo'],
    ['country' => 'Suíça', 'capital' => 'Berna'],
    ['country' => 'Suriname', 'capital' => 'Paramaribo'],
    ['country' => 'Tailândia', 'capital' => 'Bangcoc'],
    ['country' => 'Taiwan', 'capital' => 'Taipé'],
    ['country' => 'Tajiquistão', 'capital' => 'Duchambe'],
    ['country' => 'Tanzânia', 'capital' => 'Dodoma'],
    ['country' => 'Timor-Leste', 'capital' => 'Díli'],
    ['country' => 'Togo', 'capital' => 'Lomé'],
    ['country' => 'Tonga', 'capital' => 'Nucualofa'],
    ['country' => 'Trinidad e Tobago', 'capital' => 'Porto de Espanha'],
    ['country' => 'Tunísia', 'capital' => 'Túnis'],
    ['country' => 'Turcomenistão', 'capital' => 'Ashgabat'],
    ['country' => 'Turquia', 'capital' => 'Ancara'],
    ['country' => 'Tuvalu', 'capital' => 'Funafuti'],
    ['country' => 'Ucrânia', 'capital' => 'Kiev'],
    ['country' => 'Uganda', 'capital' => 'Campala'],
    ['country' => 'Uruguai', 'capital' => 'Montevidéu'],
    ['country' => 'Uzbequistão', 'capital' => 'Tashkent'],
    ['country' => 'Vanuatu', 'capital' => 'Port Vila'],
    ['country' => 'Vaticano', 'capital' => 'Cidade do Vaticano'],
    ['country' => 'Venezuela', 'capital' => 'Caracas'],
    ['country' => 'Vietnã', 'capital' => 'Hanói'],
    ['country' => 'Zâmbia', 'capital' => 'Lusaca'],
    ['country' => 'Zimbábue', 'capital' => 'Harare']
];